services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: yassine
    ports:
      - "3306:3306"

  eureka-service:
    container_name: eureka-service
    build: ./sv_eurika
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 3

  client-service:
    container_name: client-service
    build: ./client
    ports:
      - "8081:8081"
    expose:
      - "8081"
    depends_on:
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientservicedb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yassine
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 3

  car-service:
    container_name: car-service
    build: ./car
    ports:
      - "8082:8082"
    expose:
      - "8082"
    depends_on:
      eureka-service:
        condition: service_healthy
      mysql:
        condition: service_started
      client-service:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carservicedb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:yassine
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      retries: 3

  gateway-service:
    container_name: gateway-service
    build: ./Gateway
    ports:
      - "8888:8888"
    expose:
      - "8888"
    depends_on:
      eureka-service:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: yassine
    ports:
      - "8090:80"
